apiVersion: v1
kind: ConfigMap
metadata:
  name: integration-monitor-config
data:
  SPRING_PROFILES_ACTIVE: "dev"
  DB_URL: "jdbc:mysql://mysql:3306/demo?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  DB_USERNAME: "appuser"