apiVersion: v1
kind: Service
metadata:
  name: integration-monitor
spec:
  selector:
    app: integration-monitor

  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

  type: ClusterIP